### ISSUE TITLE
Example of new feature for auto-pathing.

### ISSUE THREAD

**Issue by iRobsie** [awgil/ffxiv_vfallguy#3]
I know you just added this, but wanted to provide an example of my one time usage with it so far, I wanted to try it before bed. Was a wild ride 💯 

[fallguyspathing.txt](https://github.com/awgil/ffxiv_vfallguy/files/13291056/fallguyspathing.txt)
[Video example of it going bonkers](https://www.youtube.com/watch?v=LLFhKaqnWwk)

Looking forward to see what you do with this though. ❤️

**Comment by ziha904** [comment]
You didn't censor your character name, pal. Just saying

**Comment by iRobsie** [comment]
@ziha904 
Truthfully, could give a shit less. If someone's going to spend enough time looking for the exact time, frame, and area it actually appears at, good on them.
Maybe they'll temporarily ban my twitch account while they're at it. Or worse, get my alt accounts. I sure hope since you're here you're...._GASP_ not using THIS! I was simply curious what everyone was on about, and I had already farmed everything minus the title at this point, and realistically do not plan to go for it.
Perhaps since you're here, maybe you could help contribute to the pathing algorithm (not sure how it functions, didn't bother to look), or do something productive with your time.

**Comment by Spacellary** [comment]
I think @ziha904 has the best intentions in saying that, some people go out of their way to mess with you just because you touched a plugin.

**Comment by iRobsie** [comment]
Probably, I even audibly said at the time of writing this to some friends I was chatting with that "Github seems like quite the odd place for someone to troll in this sense", but alas I truly do not mind. If someone wants to send me some gil in the mail, I'll send em some chocolate back 🤣 
I think an even bigger exposition would be to set up multiple accounts watching the verify discord channels for all the venues, modding, and the likes discords, enable chat logging for non-slash commands, and recording everyone's discord-to-ffxiv names, prodding it through their posts to see if they're interacting through any modding communities or posting any mods directly or even interacting with them, then going through that path for tracking someone.
But that's just speculation on an idea.
I think looking at a fall-guys event plugin that's going to be useless in about a month and a half (it seems mostly dead already), is child's play compared to some havoc if anyone wanted to cause it.
